server:
  port: 8084

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "997478756475-02lfuo09ufgb4bnofr3k36tcabhsomor.apps.googleusercontent.com"
            client-secret: "GGOCSPX-oOr5B9G65smjy4S2cDxenS38sWkw"
            # redirect-uri: "{base_url}/login/oauth2/code/{registrationId}"
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - openid




